# SUPER PETS base config
shrine_spacing=40
shrine_separation=16
stone_of_friendship_loot_chance=0.18
giant_soul_stone_stone_cost=4
standard_pet_scale=4.0
giant_pet_scale=6.0
mount_speed_multiplier=1.0
ancient_resin_jump_factor=0.25
ancient_resin_slipperiness=0.98
ancient_resin_speed_factor=1.35
ancient_resin_slab_slipperiness=0.98
ancient_resin_slab_speed_factor=1.35
